; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0BA5706F-8F68-4B8C-B845-47781FF9C510}
AppName=TowerAttack
AppVersion=0.1
;AppVerName=TowerAttack 0.1
AppPublisher=David, Thomas, Vincent, Bas
DefaultDirName={pf}\TowerAttack
DefaultGroupName=TowerAttack
OutputBaseFilename=TowerAttackSetup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\Users\David\Dropbox\ProjectB2B\TowerAttackFinal\Data\Tower ATTACK.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Users\David\Dropbox\ProjectB2B\TowerAttackFinal\Data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\TowerAttack"; Filename: "{app}\Tower ATTACK.exe"
Name: "{commondesktop}\TowerAttack"; Filename: "{app}\Tower ATTACK.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Tower ATTACK.exe"; Description: "{cm:LaunchProgram,TowerAttack}"; Flags: nowait postinstall skipifsilent

